regidesk/urls.py
from django.conf.urls import url

from regidesk import views

app_name='regidesk'
urlpatterns = [
    url(r"^boardingpass", views.boardingpass, name="boardingpass"),
    url(r"^([A-Z0-9]{6}$)", views.boarding_overview, name="checkin_detail"),
    url(r"^([A-Z0-9]{6}).png$", views.checkin_png, name="checkin_png"),
    url(r"^overview/([a-z]+)?$", views.boarding_overview, name="boarding_overview"),
    url(r"^prepare_passes/", views.boarding_prepare, name="boarding_prepare"),
    url(r"^send_passes/", views.boarding_send, name="boarding_send"),
    url(r"^checkin/$", views.CheckInLanding.as_view(), name="check_in_scanner"),
    url(r"^checkin/(?P<access_code>[A-Z0-9]{6})/$", views.check_in_overview, name="check_in_user_view"),
    url(r"^checkin/([A-Z0-9]{6})/badge$", views.checken_in_badge, name="check_in_badge"),
    url(r"^/?$", views.redir_main, name="checkin_choose"),
]

regidesk/templates/regidesk/_bp_prepare_help.html
    <b>Body</b> may include the following variables which will be substituted in the email with a value
    specific to each proposal:
<ul>
    <li><code>{% templatetag openvariable %} user {% templatetag closevariable %}</code> e.g. {{ sample.user }}</li>
    <li><code>{% templatetag openvariable %} qrcode {% templatetag closevariable %}</code> e.g. <code>{% templatetag openvariable %} qrcode|safe {% templatetag closevariable %}</code> produces {{ sample.qrcode|safe }}</li>
    <li><code>{% templatetag openvariable %} qrcode_url {% templatetag closevariable %}</code> e.g. {{ sample.qrcode_url }}</li>
    <li><code>{% templatetag openvariable %} code {% templatetag closevariable %}</code> e.g. {{ sample.code }}</li>
    <li><code>{% templatetag openvariable %} user.attendee.ticket_type {% templatetag closevariable %}</code> e.g. {{ sample.user.attendee.ticket_type }}</li>
    <li>The variables <code>invoices</code>, <code>items_pending</code>, <code>items_purchased</code>, <code>categories_missing</code> all return lists of the relevant things</code>
</ul>

regidesk/templates/regidesk/base.html
{% extends "site_base.html" %}
{% load staticfiles %}

{% load i18n %}

{% block body_class %}reviews{% endblock %}

{% block body_outer %}
<div class="l-content-page">
<div class="l-content-page--richtext">
<div class="rich-text">

  <div class="row">
    <div class="col-md-10">
      {% block body %}
      {% endblock %}
    </div>
  </div>
</div></div></div>
{% endblock %}
{% block extra_script %}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs/jszip-2.5.0/dt-1.10.16/b-1.4.2/b-colvis-1.4.2/b-flash-1.4.2/b-html5-1.4.2/b-print-1.4.2/cr-1.4.1/fc-3.2.3/fh-3.1.3/r-2.2.0/rg-1.0.2/datatables.min.css"/>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/v/bs/jszip-2.5.0/dt-1.10.16/b-1.4.2/b-colvis-1.4.2/b-html5-1.4.2/b-print-1.4.2/cr-1.4.1/fc-3.2.3/fh-3.1.3/r-2.2.0/rg-1.0.2/datatables.min.js"></script>
<script type="text/javascript">
        $("table.table-data").dataTable({
            "dom": "<'row'<'col-md-3'l><'col-md-3'B><'col-md-4'f>r>t<'row'<'col-md-3'i><'col-md-5'p>>",
            "stateSave": true,
            "lengthMenu": [[10, 50, 100, -1], [10, 50, 100, "All"]],
            "pageLength": 100,
            "colReorder": true,
            "buttons": [ {
              extend: 'collection',
              text: 'Export',
              buttons: ["copy", "csv", "print"]
            },
            { extend: 'collection',
              text: 'Columns',
              buttons: [
                { extend: 'columnsToggle',
                  columns: '.toggle' },
              ]
        }]});
    </script>
{% endblock %}

regidesk/templates/regidesk/boardingpass.html
{% extends "regidesk/base.html" %}

{% load i18n %}
{% load registrasion_tags %}
{% load lca2018_tags %}
{% items_purchased as purchased %}
{% items_pending as pending %}
{% items_purchased 1 as ticket %}
{% total_items_purchased 2 as penguin_dinner_count %}
{% total_items_purchased 3 as speakers_dinner_count %}
{% total_items_purchased 4 as pdns_count %}
{% ticket_type as ticket_type %}

{% block header_title %}
<h1>Boarding Pass for {{ attendee.user.email }}</h1>
<div class="panel panel-info">
    <p>This boarding pass was prepared at {{ boardingpass.created }} and was correct at that time.</p>
    <p>For an up-to-date list of paid/unpaid items please see <a href="/tickets/review">this review page.</a></p>
</div>
{% endblock %}

{% block body %}
    <div>{{ boardingpass_body|safe }}</div>
{% endblock %}

regidesk/templates/regidesk/boardingpass_overview.html
{% extends "regidesk/base.html" %}

{% load i18n %}
{% load registrasion_tags %}
{% load lca2018_tags %}
{% items_purchased as purchased %}
{% items_pending as pending %}
{% items_purchased 1 as ticket %}
{% total_items_purchased 2 as penguin_dinner_count %}
{% total_items_purchased 3 as speakers_dinner_count %}
{% total_items_purchased 4 as pdns_count %}
{% ticket_type as ticket_type %}

{% block body_class %}{{ block.super }} review-results{% endblock %}

{% block extra_style %}
{{ block.super }}
    <style type="text/css">
        .table-striped tbody tr.selected td {
            background-color: #F7F4E6;
        }
    </style>
{% endblock %}

{% block header_title %}
    <div>
        <a type=button" class="btn btn-primary btn-lg" href="{% url 'regidesk:check_in_scanner' %}">Go to scanning page</a>
    </div>
{% endblock %}

{% block body %}

    <h1>Boarding Pass Overview</h1>

    <form class="form-horizontal" method="post" action="{% url "regidesk:boarding_prepare" %}">

        {% csrf_token %}
        <p>
            Select one or more attendees (<span class="action-counter">0</span> currently selected)
            <br/>
            then pick an email template
            <select name="template">
                <option value="">[blank]</option>
                {% for template in templates %}
                    <option value="{{ template.pk }}">{{ template.label }}</option>
                {% endfor %}
            </select>
            <br/>
            <button id="next-button" type="submit" class="btn btn-primary" disabled>Next <i class="fa fa-chevron-right"></i></button>
        </p>

        <table class="table table-striped table-bordered dataTable">
            <thead>
                <th><input type="checkbox" id="action-toggle"></th>
                <th class="toggle">#</th>
                <th>Attendee Name</th>
                <th>Ticket Type</th>
                <th class="toggle">Attendee email</th>
                <th class="toggle">Checkin Code</th>
                <th>Notified?</th>
            </thead>

            <tbody>
                {% for attendee in attendees %}
                    <tr>
                        <td><input class="action-select" type="checkbox" name="_selected_action" value="{{ attendee.pk }}"></td>
                        <td>{{ attendee.id }}</td>
                        <td>{{ attendee.attendeeprofilebase.attendeeprofile.name }}</td>
                        <td>{{ attendee.ticket_type }}</td>
                        <td>{{ attendee.user.email }}</td>
                        <td>{% if attendee.user.checkin.code %}
                            <a href="{% url 'regidesk:check_in_user_view' attendee.user.checkin.code %}">{{ attendee.user.checkin.code }}</a>{% endif %}</td>
                        <td>
                            {% if attendee.user.checkin %}
                              {% if attendee.user.checkin.boardingpass %}
                                Boarding pass sent<br/>
                              {% else %}
                                Checkin Created
                              {% endif %}
                            {% else %}
                              Pending
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </form>
{% endblock %}

{% block extra_script %}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs/jszip-2.5.0/dt-1.10.16/b-1.4.2/b-colvis-1.4.2/b-flash-1.4.2/b-html5-1.4.2/b-print-1.4.2/cr-1.4.1/fc-3.2.3/fh-3.1.3/r-2.2.0/rg-1.0.2/datatables.min.css"/>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/v/bs/jszip-2.5.0/dt-1.10.16/b-1.4.2/b-colvis-1.4.2/b-html5-1.4.2/b-print-1.4.2/cr-1.4.1/fc-3.2.3/fh-3.1.3/r-2.2.0/rg-1.0.2/datatables.min.js"></script>
    <script type="text/javascript">
        (function($) {
            $.fn.actions = function(opts) {
                var options = $.extend({}, $.fn.actions.defaults, opts);
                var actionCheckboxes = $(this);
                checker = function(checked) {
                    $(actionCheckboxes).prop("checked", checked)
                        .parent().parent().toggleClass(options.selectedClass, checked);
                }
                updateCounter = function() {
                    var sel = $(actionCheckboxes).filter(":checked").length;
                    $(options.counterContainer).html(sel);
                    $(options.allToggle).prop("checked", function() {
                        if (sel == actionCheckboxes.length) {
                            value = true;
                        } else {
                            value = false;
                        }
                        return value;
                    });
                    if (sel == 0) {
                        $("#next-button").prop("disabled", true);
                    } else {
                        $("#next-button").prop("disabled", false);
                    }
                }
                // Check state of checkboxes and reinit state if needed
                $(this).filter(":checked").each(function(i) {
                    $(this).parent().parent().toggleClass(options.selectedClass);
                    updateCounter();
                });
                $(options.allToggle).click(function() {
                    checker($(this).prop("checked"));
                    updateCounter();
                });
                lastChecked = null;
                $(actionCheckboxes).click(function(event) {
                    if (!event) { var event = window.event; }
                    var target = event.target ? event.target : event.srcElement;
                    if (lastChecked && $.data(lastChecked) != $.data(target) && event.shiftKey == true) {
                        var inrange = false;
                        $(lastChecked).prop("checked", target.checked)
                            .parent().parent().toggleClass(options.selectedClass, target.checked);
                        $(actionCheckboxes).each(function() {
                            if ($.data(this) == $.data(lastChecked) || $.data(this) == $.data(target)) {
                                inrange = (inrange) ? false : true;
                            }
                            if (inrange) {
                                $(this).prop("checked", target.checked)
                                    .parent().parent().toggleClass(options.selectedClass, target.checked);
                            }
                        });
                    }
                    $(target).parent().parent().toggleClass(options.selectedClass, target.checked);
                    lastChecked = target;
                    updateCounter();
                });
            }
            /* Setup plugin defaults */
            $.fn.actions.defaults = {
                counterContainer: "span.action-counter",
                allToggle: "#action-toggle",
                selectedClass: "selected"
            }
        })($);
        $(function() {
            $("tr input.action-select").actions();
        });
        $('.dataTable').dataTable({
            "dom": "<'row'<'col-md-3'l><'col-md-3'B><'col-md-4'f>r>t<'row'<'col-md-3'i><'col-md-5'p>>",
            "stateSave": true,
            "lengthMenu": [[10, 50, 100, -1], [10, 50, 100, "All"]],
            "drawCallback": function( settings ) {
                $("tr input.action-select").actions();
            },
            "pageLength": 100,
            "colReorder": true,
            "buttons": [ {
              extend: 'collection',
              text: 'Export',
              buttons: ["copy", "csv", "print"]
            },
            { extend: 'collection',
              text: 'Columns',
              buttons: [
                { extend: 'columnsToggle',
                  columns: '.toggle' },
            ]
        }]});
    </script>
{% endblock %}

regidesk/templates/regidesk/boardingpass_prepare.html
{% extends "regidesk/base.html" %}

{% load i18n %}
{% load registrasion_tags %}
{% load lca2018_tags %}
{% items_purchased as purchased %}
{% items_pending as pending %}
{% items_purchased 1 as ticket %}
{% total_items_purchased 2 as penguin_dinner_count %}
{% total_items_purchased 3 as speakers_dinner_count %}
{% total_items_purchased 4 as pdns_count %}
{% ticket_type as ticket_type %}


{% block body %}
    <h1>BoardingPass Preparation</h1>

    <div class="row">
        <div class="col-md-4">
            <h2>Attendees</h2>
            <table class="table table-striped table-compact">
                {% for attendee in attendees %}
                  {% with profile=attendee.attendeeprofilebase.attendeeprofile %}
                    <tr>
                        <td>
                            <strong>{{ profile.name }}</strong> ({{ attendee.user.email }})<br />
                            {{ attendee.ticket_type }}<br/>
                            {{ profile.company }}<br/>
                            {{ profile.free_text_1 }}<br/>
                            {{ profile.free_text_2 }}<br/>
                        </td>
                    </tr>
                    {% endwith %}
                {% endfor %}
            </table>
        </div>
        <div class="col-md-6">
            <h2>Email</h2>

            <form class="form-horizontal" method="post" action="{% url "regidesk:boarding_send" %}">

                {% csrf_token %}

                <label>From Address</label>
                <input type="text" name="from_address" class="span5 label-required" value="{{ template.from_address }}" />
                <br/>
                <label>Subject</label>
                <input type="text" name="subject" class="span5" value="{{ subject }}" />
                <br/>
                <label>Template</label>
                <a href=" {% url 'admin:regidesk_boardingpasstemplate_change' template.id %}">
                    <input type="text" readonly class="form-control-plaintext span5" value="{{ template.label }}">
                </a>
                <div class="panel panel-default">
                    <ul class="nav nav-tabs panel-heading" id="templates" role="tablist">
                        <li class="nav-item"><a class="nav-link active" id="plain_template" data-toggle="tab" href="#plain" role="tab" aria-selected="true">Plaintext</a></li>
                        <li class="nav-item"><a class="nav-link" id="html_template" data-toggle="tab" href="#html" role="tab" aria-selected="false">HTML</a></li>
                    </ul>
                    <div class="tab-content panel-body" id="templatesContent">
                        <div class="tab-pane active monospace-text" id="plain" role="tabpanel" aria-labelledby="plain_template">{{ rendered_template.plain }}</div>
                        <div class="tab-pane fade show" id="html" role="tabpanel" aria-labelledby="html_template">{{ rendered_template.html }}</div>
                    </div>
                </div>
                <input type="hidden" name="notification_template" value="{{ template.pk }}" />
                <input type="hidden" name="attendees" value="{{ attendees }}" />

                {% include "regidesk/_bp_prepare_help.html" %}

                <button type="submit" class="btn btn-primary">Send {{ attendees|length }} Email{{ attendees|length|pluralize }}</button>
                <a class="btn" href="{% url "regidesk:boarding_overview" %}">Cancel</a>
            </form>
        </div>
    </form>
{% endblock %}

regidesk/templates/regidesk/ci_code_404.html
{% extends "regidesk/base.html" %}


{% block header_title %}
   <h3>404 code not found</h3>
{% endblock %}

{% block body %}
    <a type=button" class="btn btn-primary btn-lg" href="{% url 'regidesk:check_in_scanner' %}">Return to scanning page</a>
    <a type=button" class="btn btn-primary btn-lg pull-right" href="{% url 'regidesk:boarding_overview' %}">Go to overview</a>
{% endblock %}

regidesk/templates/regidesk/ci_landing.html
{% extends "regidesk/base.html" %}

{% block header_title %}
    <h1>Boarding pass lookup</h1>
    <p>Please scan or enter boarding pass code and click "Look Up"</p>
{% endblock %}


{% block body %}
    <div>
        <div id="code_div" class="form-group has-feedback has-error">
            <label class="control-label" for="bpcode">Boarding Pass Code</label>
            <input id="bptext" type="text" class="form-control" id="bpcode" placeholder="Code">
            <span id="input_icon" class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
            <span id="help_ok" class="help-block" style="display: none;">Format appears OK</span>
            <span id="help_ur" class="help-block" style="display: block;">Format doesn't match</span>
        </div>
        <button id="bpredir" class="btn btn-primary">Submit</button>
        <button id="clear" class="btn btn-danger">Clear</button>
        <a type=button" class="btn btn-info pull-right" href="{% url 'regidesk:boarding_overview' %}">Overview</a>
    </div>
    <script type="text/javascript">
        var code_div = document.getElementById("code_div");
        var icon = document.getElementById("input_icon");
        var tb = document.getElementById("bptext");
        var ok = document.getElementById("help_ok");
        var unk = document.getElementById("help_ur");
        var re = new RegExp('^[A-Z0-9]{6}$');
        document.getElementById("bpredir").onclick = function() {
            location.href = tb.value;
        };
        document.getElementById("clear").onclick = function() {
            tb.value = "";
        };
        tb.oninput = function() {
            is_good = re.test(tb.value);
            if (is_good) {
                code_div.className = "form-group has-feedback has-success";
                icon.className = "glyphicon glyphicon-ok form-control-feedback";
                ok.style.display = "block";
                unk.style.display = "none";
            } else {
                code_div.className = "form-group has-feedback has-error";
                icon.className = "glyphicon glyphicon-remove form-control-feedback";
                ok.style.display = "none";
                unk.style.display = "block";
            }
            console.log(is_good);
        };
    </script>
{% endblock %}

regidesk/templates/regidesk/ci_overview.html
{% extends "regidesk/base.html" %}


{% block header_title %}
   <h3>Pre-print check</h3>
{% endblock %}


{% block body %}
    {% load registrasion_tags %}
    {% load lca2018_tags %}
    {% items_purchased as purchased %}
    {% items_pending as pending %}
    {% items_purchased 1 as ticket %}
    {% items_purchased 6 as shirts %}
    {% total_items_purchased 3 as penguin_dinner_count %}
    {% total_items_purchased 4 as speakers_dinner_count %}
    {% total_items_purchased 5 as pdns_count %}
    {% ticket_type as ticket_type %}

    <div class="panel panel-default">
        <div class="panel-heading">Content Check</div>
        <div class="panel-body">
            <dl class="dl-horizontal">
                <dt>Ticket type</dt><dd>{{ ticket_type }}</dd>
                <dt>Name</dt><dd>{{ user.attendee.attendeeprofilebase.attendeeprofile.name }}</dd>
                <dt>Company</dt><dd>{% if ticket_type == "Student" or ticket_type == "Hobbyist" or "Only" in ticket_type %}{% else %}{{ user.attendee.attendeeprofilebase.attendeeprofile.company }}{% endif %}</dd>
                <dt>Free Text 1</dt><dd>{{ user.attendee.attendeeprofilebase.attendeeprofile.free_text_1 }}</dd>
                <dt>Free Text 2</dt><dd>{{ user.attendee.attendeeprofilebase.attendeeprofile.free_text_2 }}</dd>
                <dt>Penguin Dinner Tickets</dt><dd>{{ penguin_dinner_count }}</dd>
                <dt>Spearker Dinner Tickets</dt><dd>{{ speakers_dinner_count }}</dd>
                <dt>PDNS Tickets</dt><dd>{{ pdns_count }}</dd>
                <dt>Over 18 years</dt><dd>{% if user.attendee.attendeeprofilebase.attendeeprofile.of_legal_age %}yes{% else %}<strong class="red">NO</strong>{% endif %}</dd>
                <dt>Username</dt><dd>{{ user.username }}</dd>
            </dl>
            <table class="table table-striped">
                <tr>
                    <th>item</th>
                    <th>count</th>
                </tr>
                {% for shirt in shirts%}
                    <tr>
                        <td>{{ shirt.product }}</td>
                        <td>{{ shirt.quantity }}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>

    <div class="panel {% if check_in.checked_in_bool %}panel-danger{% else %}panel-success{% endif %}">
        <div class="panel-heading">Check In</div>
        <div class="panel-body">
            <dl class="dl-horizontal">
                <dt>Status</dt><dd>{% if check_in.checked_in_bool %}Checked in{% else %}Not checked in{% endif %}</dd>
            </dl>
            <blockquote>
                <p>If an attendee sees an error with their contents, please instruct them to change their profile and come back before checking them in.</p>
                <p>The attendee will be unable to edit their profile after they have been checked in</p>
            </blockquote>
            <form method="post">
                <input type="checkbox" name="checkin" value="checkin" checked hidden>
                <input class="btn {% if check_in.badge_printed %}btn-danger{% else %}btn-success{% endif %} pull-right" type="submit" value="Submit">
            </form>
        </div>
    </div>


    <div class="panel {% if check_in.badge_printed %}panel-danger{% else %}panel-success{% endif %}">
        <div class="panel-heading">Badge</div>
        <div class="panel-body">
            <dl class="dl-horizontal">
                <dt>Status</dt><dd>{% if check_in.badge_printed %}Marked{% else %}Not marked{% endif %} as printed</dd>
            </dl>
            <form method="post" hidden>
                <input type="checkbox" name="badge" value="badge" checked hidden>
                <a type="button" class="btn btn-primary" href="badge">Show Badge</a>
                <input class="btn {% if check_in.badge_printed %}btn-danger{% else %}btn-success{% endif %} pull-right" type="submit" value="Submit">
            </form>
            <form method="post">
                <input type="checkbox" name="unbadge" value="unbadge" checked hidden>
                <input class="btn btn-danger pull-right" type="submit" value="Force Reprint">
            </form>
        </div>
    </div>

    <div class="panel {% if check_in.schwag_given %}panel-danger{% else %}panel-success{% endif %}">
        <div class="panel-heading">Schwag</div>
        <div class="panel-body">
            <dl class="dl-horizontal">
                <dt>Status</dt><dd>{% if check_in.schwag_given %}Marked{% else %}Not marked{% endif %} as given</dd>
            </dl>
            <form method="post">
                <input type="checkbox" name="schwag" value="schwag" checked hidden>
                <input class="btn {% if check_in.schwag_given %}btn-danger{% else %}btn-success{% endif %} pull-right" type="submit" value="Submit">
            </form>
        </div>
    </div>

    <div class="panel panel-warning">
        <div class="panel-heading">Log Exception</div>
        <div class="panel-body">
            <form method="post">
                <textarea class="form-control" rows="3" name="exception">{{ check_in.review_text }}</textarea>
                <p class="help-block">Reminder: Please tell attendee to email boarding@lca2018.org with the details as well</p>
                <input class="btn btn-warning pull-right" type="submit" value="Submit">
            </form>
        </div>
    </div>

    <div class="panel {% if check_in.checked_in_bool or check_in.schwag_given %}panel-danger{% else %}panel-success{% endif %}">
        <div class="panel-heading">Bulk actions</div>
        <div class="panel-body">
            <p>Mark attendee as checked in and schwag given</p>
            <dl class="dl-horizontal">
                <dt>Status</dt><dd>{% if check_in.checked_in_bool or check_in.schwag_given %}One of the items in bulk action is marked as given already{% else %}Both items are marked as unrecived{% endif %}</dd>
            </dl>
            <form method="post">
                <input type="checkbox" name="bulk" value="bulk" checked hidden>
                <input class="btn  {% if check_in.checked_in_bool or check_in.schwag_given %}btn-danger{% else %}btn-success{% endif %} pull-right" type="submit" value="Submit">
            </form>
        </div>
    </div>
    <a type=button" class="btn btn-primary btn-lg" href="{% url 'regidesk:check_in_scanner' %}">Return to scanning page</a>

{% endblock %}